---

# Default compose file for development and production.
# Should be used directly in development.
# Automatically loads `docker-compose.override.yml` if it exists.
# No extra steps required.
# Should be used together with `docker/docker-compose.prod.yml`
# in production.

services:
  db:
    image: "postgres:18-alpine"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-net
    env_file: ./config/.env
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s

  minio:
    image: "minio/minio:latest"
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - web-net
    env_file: ./config/.env
    healthcheck:
      test: mc ready local || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  web:
    <<: &web
      # Image name is changed in production:
      image: "photo-album:dev"
      build:
        target: development_build
        context: .
        dockerfile: ./docker/django/Dockerfile
        args:
          DJANGO_ENV: development
        cache_from:
          - "photo-album:dev"
          - "photo-album:latest"
          - "*"

      volumes:
        - django-static:/var/www/django/static
      depends_on:
        db:
          condition: service_healthy
        minio:
          condition: service_healthy
      networks:
        - web-net
        - postgres-net
      env_file: ./config/.env
      environment:
        DJANGO_DATABASE_HOST: db
        POETRY_CACHE_DIR: /tmp/poetry-cache

    command: python -We -bb manage.py runserver 0.0.0.0:8000
    healthcheck:
      test: /bin/sh /code/docker/django/healthcheck.sh
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  webdav:
    <<: *web
    command: python manage.py run_webdav_server --verbose=5
    ports:
      - "8080:8080"
    healthcheck:
      test: python -c "import socket; s=socket.socket(); s.connect(('localhost', 8080)); s.close()"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  # Network for postgres, use it for services that need access to the db:
  postgres-net:
  # Network for your internals, use it by default:
  web-net:

volumes:
  postgres-data:
  minio-data:
  django-static:
